  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: ${{ secrets.KAKAO_CLIENT_ID }}
            client-secret: ${{ secrets.KAKAO_CLIENT_SECRET }}
            redirect-uri: ${{ secrets.KAKAO_REDIRECT_URI }}
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope:
              - profile_nickname
              - account_email

        provider:
          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            user-name-attribute: id