#name: Deploy to Amazon EC2
#
#on:
#  push:
#    branches:
#      - 'develop'
#  pull_request:
#    branches:
#      - 'develop'
#
## 리전, 버킷 이름, CodeDeploy 앱 이름, CodeDeploy 배포 그룹 이름
#
#
#permissions:
#  contents: read
#
#jobs:
