on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'feature/*'
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          character set server: 'utf8'
          mysql database: 'sosim_db'
          mysql user: 'user01'
          mysql password: 'user01'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      ## create application-database.yaml
      - name: make application-database.yaml
        run: |
          # create application-database.yaml
           cd ./src/main/resources
          # application-database.yaml 파일 생성
           touch ./application-database.yaml
          # GitHub-Actions 에서 설정한 값을 application-database.yaml 파일에 쓰기
          echo "${{ secrets.DATABASE }}" >> ./application-database.yaml
        shell: bash


      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Test with Gradle
        run: ./gradlew test